# Generated by Django 5.1.1 on 2024-10-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szakNev', models.CharField(max_length=50)),
                ('tamogatott', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Szak megnevezése',
            },
        ),
        migrations.CreateModel(
            name='Felvetelizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50)),
                ('szul_evszam', models.IntegerField()),
                ('pontszam', models.IntegerField()),
                ('szak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felviadmin.szak')),
            ],
            options={
                'verbose_name_plural': 'Felveteliző neve',
            },
        ),
    ]
